version: "3.8"

networks:
  docker-dou-test-net:
    driver: bridge

services:
  nginx:
    # Nginx
    container_name: dou-nginx
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.platform/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - docker-dou-test-net
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - dou-nestjs
      - dou-flask
    links:
      - dou-nestjs
      - dou-flask

  dou-nestjs:
    # nestJS
    container_name: dou-nestjs
    build:
      context: ./DOU_Nest
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      # - ./DOU_Nest/node_modules:/nestfolder/node_modules
      - ./DOU_Nest/src:/nestfolder/src
    env_file:
      - .env.docker
    networks:
      - docker-dou-test-net

  dou-flask:
    # Flask
    container_name: dou-flask
    build:
      context: ./DOU_Flask
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./DOU_Flask:/app/flask
    networks:
      - docker-dou-test-net
