version: "3.8"

networks:
  docker-dou-test-net:
    driver: bridge

services:
  dou-nestjs:
    # nestJS
    container_name: dou-nestjs
    build:
      context: ./DOU_Nest
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./DOU_Nest/src:/nestfolder/src
    env_file:
      - ./.env.docker
    networks:
      - docker-dou-test-net

  dou-mysql:
    # mysql
    container_name: dou-mysql
    image: mysql:latest
    # platform: linux/amd64
    environment:
      MYSQL_DATABASE: "docker_dou_test"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_HOST: "%"
    ports:
      - 3307:3306
    networks:
      - docker-dou-test-net

  dou-flask:
    # Flask
    container_name: dou-flask
    build:
      context: ./DOU_Flask
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./DOU_Flask/:/flaskfolder/
    networks:
      - docker-dou-test-net
