name: Docker Image CI

on:
  pull_request: # pull request -> merge 가 되었을 때 Github Action 실행!
    types: [closed]
  workflow_dispatch: # 수동 실행도 가능하도록 함

jobs:
  build:
    runs-on: ubuntu_latest
    steps:
      - uses: actions/checkout@v3
      - name: Login DockerHub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker Image
        run: docker build -t dou_repo .

      - name: taging
        run: docker tag dou_repo:latest silverage22/dou_repo:latest

      - name: Push to Dockerhub
        run: docker push silverage22/dou_repo:latest
