name: Docker Image CI

on:
  pull_request: # pull request -> merge 가 되었을 때 Github Action 실행!
    types: [closed]
  workflow_dispatch: # 수동 실행도 가능하도록 함

jobs:
  build:
    # pull 요청이 develop에 merge 되었을 때 아래 steps를 실행
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop'

    runs-on: ubuntu_latest
    steps:
      - uses: actions/checkout@v3
      - run: docker compose up -d
